---
- name: Build, tag, and push Docker image
  hosts: localhost
  tasks:
    - name: Build Docker image
      command: docker build -t yourdockerid/jenkinsapp:latest /root/project

    - name: Push Docker image
      command: docker push yourdockerid/jenkinsapp:latest

- name: Deploy container on Docker host
  hosts: docker
  tasks:
    - name: Stop old container
      command: docker rm -f jenkinsapp || true

    - name: Pull latest image
      command: docker pull yourdockerid/jenkinsapp:latest

    - name: Run new container
      command: docker run -d --name jenkinsapp -p 80:80 yourdockerid/jenkinsapp:latest
